AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Streams DynamoDB table changes to EventBridge (uksb-1tthgi812) (tag:dynamodb-eventbridge-java)
Globals:
  Function:
    Runtime: java17
    Timeout: 30
    MemorySize: 512
    Architectures:
      - x86_64
    Handler: telran.pulse.monitoring.App::handleRequest
    Environment:
      Variables:
        LOGGING_LEVEL: FINER
  

Resources:
  RangeProvider:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: range-provider
      Events:
        RandeProviderAPI:
          Type: Api
          Properties:
            Path: /range
            Method: get

  PulseLastValue:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: pulse-last-value
      PrimaryKey:
        Name: patientId
        Type: Number

  PulseJumpValues:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName:  pulse-jump-values
      AttributeDefinitions:
        - AttributeName: patientId
          AttributeType: N
        - AttributeName: timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: patientId
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  PulseValuesStream:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: pulse-data
      AttributeDefinitions:
        - AttributeName: patientId
          AttributeType: N
        - AttributeName: timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: patientId
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
          StreamViewType: NEW_IMAGE

  AbnormalPulseValues:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: pulse-abnormal-values 
      AttributeDefinitions:
        - AttributeName: patientId
          AttributeType: N
        - AttributeName: timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: patientId
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5


  PulseJumpAnalyzer:
   Type: 'AWS::Serverless::Function'
   Properties:
      CodeUri: pulse-jump-analyzer
      Environment:
        Variables:
          FACTOR: '0.1'
      Events:
        TableRecordChange:
          Type: DynamoDB
          Properties:
            StartingPosition: LATEST
            Stream: !GetAtt PulseValuesStream.StreamArn
            FilterCriteria:
              Filters:
                - Pattern: '{"eventName": ["INSERT"]}'
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PulseJumpValues
        - DynamoDBCrudPolicy:
            TableName: !Ref PulseLastValue

  PulseValuesAnalyzer:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: pulse-values-analyzer
      Environment:
        Variables:
          RANGE_PROVIDER_API: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/range"
      Events:
        TableRecordChange:
          Type: DynamoDB
          Properties:
            StartingPosition: LATEST
            Stream: !GetAtt PulseValuesStream.StreamArn
            FilterCriteria:
              Filters:
                - Pattern: '{"eventName": ["INSERT"]}'
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AbnormalPulseValues